permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 6chen
  email: suyan0830@gmail.com
  link: http://yansu.org
  weibo: http://weibo.com/yansu0711
  github: http://github.com/suyan

# 站点信息
title: YuSin的博客
description: YuSin的博客
url: http://6chen.github.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://vi0.6rooms.com/live/2015/01/19/08/1002v1421628503897913940_b.jpg
favicon: http://vi0.6rooms.com/live/2015/01/19/08/1002v1421628503897913940_b.jpg

# google analytics 设置
ga:
  id: #UA-54767140-1
  url: #yansu.org

# disqus 设置
disqus:
  shortname: 6chen

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
